### PR TITLE
calc_* and process_hms functions; .gitignore

### PR DESCRIPTION
**Pull request by mitchellmanware**
I was unable to resolve errors in previous pull requests, so with new branch (v2) I will commit small changes to evaluate how they do/do not pass pull request tests.

### CODE REVIEW

**Comment by mitchellmanware** [comment]
@Spatiotemporal-Exposures-and-Toxicology

All checks are failing due to:
```
 Error: 
  ! error in pak subprocess
  Caused by error in `verify_extracted_package(filename, pkg_cache)`:
  ! 
  '/tmp/RtmpyxpY6v/file13cf7aaebd0c/src/contrib/x86_64-pc-linux-gnu-ubuntu-22.04/4.3/withr_3.0.0.tar.gz'
  is not a valid binary, it is missing withr/Meta/package.rds.
  ---
  Backtrace:
  1. pak::lockfile_install(".github/pkg.lock")
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
 ```
Unclear why this is occurring, and seems weird that 4 R files (which pass local lints and are not subject to testing) and edits to the .gitignore cause these issues. Do you have any idea why this is happening?

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@mitchellmanware Not sure why. Did you need to add all of those sub-paths to the .gitignore?

**Comment by mitchellmanware** [comment]
@Spatiotemporal-Exposures-and-Toxicology 
Those are the folders with raw covariate data, but I guess those can be put into one single `raw_data/` folder and have just that on the .gitignore.

**Comment by mitchellmanware** [comment]
Seems to be an issue with the new version of the `withr` package published yesterday. GitHub dialogue has opened for fixes-  I will keep updating.

Discussion- https://github.com/r-lib/withr/issues/253
Package- https://cran.r-project.org/web/packages/withr/index.html

**Comment by mitchellmanware** [comment]
@Spatiotemporal-Exposures-and-Toxicology @sigmafelix @eva0marques @dzilber @MAKassien @dawranadeep @Sanisha003 
In case anyone else is experiencing PR check related issues

**Comment by mitchellmanware** [comment]
R-CMD-check build finally passes due to updates to `withr` package.

- [ ] URL checks within download functions are not covered by unit tests
- [ ] pkgdown fail- may be due to .qmd file in vignettes

**Comment by mitchellmanware** [comment]
URLs generated by `download_sedac*` always return HTTP status 200 because the `httr::GET()` returns the NASA EarthData login page. Removed for now but will continue to work on these within function URL checks.

**Pull request merged**
