### PR TITLE
Kpm meta learner 02

### PR DESCRIPTION
**Pull request by Spatiotemporal-Exposures-and-Toxicology**

### CODE REVIEW

**Comment by sigmafelix** [comment]
I found that the metalearner task development and test issue is assigned to me. I will make a pull request from `kpm-meta-learner-02` to my branch then work on the issue. Do we need to apply the repository pull request protocol to "branch-to-branch" pulls?

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix  @eva0marques  I think y'all have taken this pull request and are moving it forward on your own branch. Is it okay for me to close this pull request and delete the branch (i.e. abandon the branch)?

**Comment by eva0marques** [comment]
@Spatiotemporal-Exposures-and-Toxicology  I think so, I am working on a clone of Insang branch. I let @sigmafelix confirm it is all good.

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology @eva0marques I agree. I will work with Eva to make a pull request for metalearner.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@eva0marques @sigmafelix  Closed, but I'll hold off on deleting the branch for the time being - until your metalearner prediction work is merged into main.

**Pull request closed without merging**
